Testing
YunoHost-Apps/minidlna_ynh pull request #18
Opened 2020-09-29 11:01 UTC by kay0u

2020-09-29 11:55 UTC, ericgaspar requested changes
Some typo stuff. I should probably push a PR for that...

2020-09-29 11:55 UTC, ericgaspar commented on README.md
> +* Jessie x86-64b - [![](https://ci-stretch.nohost.me/ci/logs/minidlna%20%28Apps%29.svg)](https://ci-stretch.nohost.me/ci/apps/minidlna/)
```suggestion

```
Jessie is dead, long live Buster

2020-09-29 11:55 UTC, ericgaspar commented on README_fr.md
> +* Jessie x86-64b - [![](https://ci-stretch.nohost.me/ci/logs/minidlna%20%28Apps%29.svg)](https://ci-stretch.nohost.me/ci/apps/minidlna/)
```suggestion

```

2020-09-29 11:55 UTC, ericgaspar commented on app_minidlna_fr.md
>  ### Comment consulter et lire les fichiers multimédias partagés par minidlna?
```suggestion
### Comment consulter et lire les fichiers multimédias partagés par MiniDLNA?
```

2020-09-29 11:55 UTC, ericgaspar commented on scripts/actions/install_backports
> +ynh_script_progression --message="Re-installing minidlna from backports..." --weight=9
```suggestion
ynh_script_progression --message="Re-installing MiniDLNA from backports..." --weight=9
```

2020-09-29 11:55 UTC, ericgaspar commented on scripts/actions/install_standard
> +ynh_script_progression --message="Re-installing minidlna from stable..." --weight=9
```suggestion
ynh_script_progression --message="Re-installing MiniDLNA from stable..." --weight=9
```

2020-09-29 11:55 UTC, ericgaspar commented on scripts/backup
> +ynh_script_progression --message="Backing up minidlna configuration..."
```suggestion
ynh_script_progression --message="Backing up MiniDLNA configuration..."
```

2020-09-29 11:55 UTC, ericgaspar commented on scripts/install
> +ynh_script_progression --message="Installing minidlna..." --weight=45
```suggestion
ynh_script_progression --message="Installing MiniDLNA..." --weight=45
```

2020-09-29 11:55 UTC, ericgaspar commented on scripts/remove
> +ynh_script_progression --message="Removal of $app completed" --last
```suggestion
ynh_script_progression --message="Removal of MiniDLNA completed" --last
```

2020-09-29 11:55 UTC, ericgaspar commented on scripts/restore
> +ynh_script_progression --message="Installing minidlna" --weight=45
```suggestion
ynh_script_progression --message="Installing MiniDLNA" --weight=45
```

2020-09-29 11:55 UTC, ericgaspar commented on app_minidlna.md
>  Minidlna does not have a graphical interface, but does not require any special configuration.
```suggestion
MiniDLNA does not have a graphical interface, but does not require any special configuration.
```

2020-09-29 11:55 UTC, ericgaspar commented on app_minidlna.md
> +Minidlna is sharing the folder /home/yunohost.multimedia/share, which is common to each user in /home/$USER/Multimedia/Share.
```suggestion
MiniDLNA is sharing the folder `/home/yunohost.multimedia/share`, which is common to each user in `/home/$USER/Multimedia/Share`.
```

2020-09-29 11:55 UTC, ericgaspar commented on app_minidlna.md
> +If [transmission](https://github.com/YunoHost-Apps/transmission_ynh) is installed, the downloaded media will be available in dlna.
```suggestion
If [Transmission](https://github.com/YunoHost-Apps/transmission_ynh) is installed, the downloaded media will be available in DLNA.
```

2020-09-29 11:55 UTC, ericgaspar commented on app_minidlna.md
>  ### How to view and play media files shared by minidlna?
```suggestion
### How to view and play media files shared by MiniDLNA?
```

2020-09-29 11:55 UTC, ericgaspar commented on app_minidlna.md
>  In any case, it is generally sufficient to seek external sources, USB etc, to find the DLNA server, displayed under the name **Yunohost DLNA**.
```suggestion
In any case, it is generally sufficient to seek external sources, USB etc., to find the DLNA server, displayed under the name **YunoHost DLNA**.
```

2020-09-29 11:55 UTC, ericgaspar commented on app_minidlna_fr.md
>  Minidlna partage le dossier /home/yunohost.multimedia/share, qui est commun à chaque utilisateur dans le dossier /home/$USER/Multimedia/Share.
```suggestion
MiniDLNA partage le dossier `/home/yunohost.multimedia/share`, qui est commun à chaque utilisateur dans le dossier `/home/$USER/Multimedia/Share`.
```

2020-10-04 08:34 UTC, ericgaspar approved these changes

2020-11-01 19:01 UTC, alexAubin approved these changes
LGTM apart from a few minor comments

2020-11-01 19:01 UTC, alexAubin commented on scripts/upgrade
> +if ! IS_PACKAGE_CHECK   # LXC doesn't allow sysctl to play with kernel options.
Dunno if that's relevant but we had a discussion in transmission a while ago about the usage of this technique ... sure that fixes tests, but that also means that the app won't install on regular LXC instances (for example, our very own infra is based on yunohost LXCs ...) which are a legit use case. One could use systemctl-detect-virt to detect that we're inside a lxc (or idk which trick we ended up using in transmission)

Anyway, I understand that the point of the PR was only to changes the syntax + add the comment :/

2020-11-03 15:10 UTC, kay0u commented on scripts/_common.sh
> +ynh_get_scalable_phpfpm () {
You're right, moreover, these helpers are not used.

2020-11-03 15:13 UTC, kay0u commented on scripts/install
> +test -z "$codename" && (ynh_die --message="codename empty")
True, but I've remove the backport list now :-)

2020-11-23 16:46 UTC, ericgaspar approved these changes

2020-12-02 15:37 UTC, merged